name: Docker Image CI

on:
  push:
    branches: ['prep/**', 'release/**', 'test/**', master]
    tags: ['**']

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Create vars
      id: vars
      run: |
        export github_tag=${{ github.ref_name }}
        export is_tag_create=false

        export rx_tag='^refs\/tags\/.*'
        export rx_version_tag='^v([0-9]+\.){0,2}(\*|[0-9]+)(-rc[0-9]*){0,1}$'
        if [[ "${{github.ref}}" =~ $rx_tag ]]; then
          export is_tag_create=true
        fi

        echo "::set-output name=github_tag::$github_tag"
        echo "::set-output name=is_tag_create::$is_tag_create"

    - name: Show environment
      run: |
        echo is_tag_create = ${{ steps.vars.outputs.is_tag_create }}
        echo github_tag = ${{ steps.vars.outputs.github_tag }}

    - name: Build the Docker image
      if: ${{ steps.vars.outputs.is_tag_create == 'true' }}
      run: |
        make docker-buildenv
        make docker-runtime
        docker build . --file dockerfile --tag filvenus/venus:latest
        docker tag filvenus/venus:latest filvenus/venus:${{ steps.vars.outputs.github_tag }}
        docker login --username=filvenus --password ${{ secrets.DOCKER_PASSWORD }}
        docker push filvenus/venus:${{ steps.vars.outputs.github_tag }}
        docker push filvenus/venus:latest
        docker push filvenus/venus-runtime:latest
        docker push filvenus/venus-buildenv:latest
